### ISSUE TITLE
Azure VM Ubuntu 14 Installation error

### ISSUE THREAD

**Issue by NicolasKramer** [KaveIO/KaveToolbox#1]
### Intro

Dear Kave Team,

I'm getting an error on a Ubuntu vm box on installation somewhere mid Bash installation script. It doesn't seem to be the fault of KAVE, but more of a missing Ubuntu repo.
### Error

```
Get:101 http://azure.archive.ubuntu.com/ubuntu/ trusty-updates/main libldap2-dev amd64 2.4.31-1+nmu2ubuntu8.1 [260 kB]
Fetched 30.8 MB in 13s (2283 kB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/f/freetype/libfreetype6-dev_2.5.2-1ubuntu2.4_amd64.deb  404  Not Found [IP: 91.189.92.200 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Traceback (most recent call last):
  File "./KaveToolbox/scripts/KaveInstall", line 189, in <module>
    component.install(kind=kind, tmpdir=tempdir, loud=(not quieter))
  File "/home/kavetest/KaveToolbox/config/libInstall.py", line 397, in install
    self.run(cmd)
  File "/home/kavetest/KaveToolbox/config/libInstall.py", line 482, in run
    return self._cleanIfFailure(cmd, self.tmpdir)
  File "/home/kavetest/KaveToolbox/config/libInstall.py", line 501, in _cleanIfFailure
    return cleanIfFailureLoud(cmd, dir)
  File "/home/kavetest/KaveToolbox/config/libInstall.py", line 160, in cleanIfFailureLoud
    raise RuntimeError("Problem running: \n" + cmd + "\n got:\n\t" + str(status))
RuntimeError: Problem running:
apt-get -y install x11-common libx11-6 x11-utils libX11-dev libgsl0-dev gsl-bin libxpm-dev libxft-dev g++ gfortran build-essential g++ libjpeg-turbo8-dev libjpeg8-dev libjpeg8-dev libjpeg-dev  libtiff5-dev libxml2-dev libssl-dev libgnutls-dev libgmp3-dev libpng12-dev libldap2-dev libkrb5-dev freeglut3-dev libfftw3-dev python-dev libmysqlclient-dev libgif-dev libiodbc2 libiodbc2-dev libxext-dev libxmu-dev libimlib2 gccxml libxml2 libglew-dev glew-utils libc6-dev-i386
 got:
    100
```

**Comment by NicolasKramer** [comment]
### Solution

I solved this by running:

```
sudo apt-get update
sudo bash <re-install KAVE>
```

Then the result is:

```
Successful install
The KAVE environment should now be added for most users automatically through etc/profile.d, if they use the bash shell. If this is not working, try $ . /opt/KaveToolbox/scripts/KaveEnv.sh manually and enjoy your software
```

**Comment by rwlambert** [comment]
Hi Nicolas,

It's great that you're testing out the installer :) The Ubuntu part is not very smooth at the moment, unfortunately, we are still working out some bugs there. 

For example we know that on ubuntu KTB installs/configures X windows system / desktop environment somehow a second time even if you do have it, and if you don't have it then the resulting installation is incomplete anyway with respect to a real desktop ubuntu version, so in the end the vncserver we can have is not actually a full remote desktop-like experience.

This is something we're trying to address for the next release, but difficult to test since there are many different ways to have that initial ubuntu installation from different images even in the same cloud environment.

Centos6 installation is the most well-tested as of today, and Centos7 installation is similar enough to have many fewer reported bugs.

Thanks for your contribution!

Rob
